### ISSUE TITLE
Keyboard to show up after entering invalid code

### ISSUE THREAD

**Issue by sydneymason** [bluenumberfoundation/humanid-ios-sdk#14]
When user enters in invalid OTP code and taps on "Close" after error message pops up, user is brought to OTP verification screen but keyboard is collapsed. Keyboard should still be there when user clicks "close" after entering in invalid OTP. 
![IMG_0973](https://user-images.githubusercontent.com/55056005/85791897-9374a680-b700-11ea-834a-3b4fb07207d3.PNG)
![IMG_0972](https://user-images.githubusercontent.com/55056005/85791901-95d70080-b700-11ea-9431-88ddf4773fe5.PNG)

**Comment by budioktaviyan** [comment]
@sydneymason Previously @bastian-purrer asked me to fix like this on [Issue#7](https://github.com/bluenumberfoundation/humanid-ios-sdk/issues/7)
