### ISSUE TITLE
User convenience - enter phone number screen & Default country

### ISSUE THREAD

**Issue by bastian-purrer** [bluenumberfoundation/humanid-ios-sdk#6]
What:
"Enter phone number" screen is not optimized for a great user experience.

Solution:
(1) The keyboard should open automatically
(2) There should be a blinking cursor in the phone number field(see image) in the moment the user reaches the page already.
(3) [see image] The field should have a default text (in grey?) "Enter Phone Number" before user starts typing
(4) Optional: Gray out "Enter" button before user starts typing
(5) The country should default to the country the user is in/registered. **If we can't recognize that, it should default to the U.S.A.** [Important!]
(6) [see image] Select the country should not use the default iOS selection 'wheel' - it's not nice to use. Instead should be similar to Android version, with search function. 

Why/KPI: Conversion rate

--
Re: (3)
![image](https://user-images.githubusercontent.com/46710651/84575732-87422e00-ad7d-11ea-914a-a2a80aaaedef.png)
---
Re (6):
![image](https://user-images.githubusercontent.com/46710651/84575796-f1f36980-ad7d-11ea-8654-b47e54f56750.png)

--
Version 1.1.1

**Comment by budioktaviyan** [comment]
For solution number 6 it is not possible for ios. default selection for ios should follow Human Interface Guideline, which is just like that.

**Comment by bastian-purrer** [comment]
not possible, or shouldn't? If not possible, why not?
